### ISSUE TITLE
Add/allow Viviana as REDCap user

### ISSUE THREAD

**Issue by adurbin2** [UCSC-Treehouse/redcap#2]
She must have user rights, since she created the first CKCC form; but when I tried to add her as a user, REDCap told me she needed to join REDCap. She will be testing and modifying instruments (forms) and entering data, but maybe shouldn't be able to delete projects or data without an admin override.

**Comment by e-t-k** [comment]
Will do. She had an account on an older installation of redcap which is no longer running; she doesn't have one on the current one.

**Comment by e-t-k** [comment]
Added Viviana and sent her login information. Added her to the CKCC project as an ordinary user; she does not have the rights to delete data.
