### ISSUE TITLE
Enable ontology search feature

### ISSUE THREAD

**Issue by adurbin2** [UCSC-Treehouse/redcap#3]
Please enable the use of ontology search feature: "Ontology search is not enabled! The biomedical ontology search feature has not yet been enabled in REDCap. Before you can utilize the feature, a REDCap Administrator must first enable it for the REDCap system."

**Comment by e-t-k** [comment]
Bioportal account has been created and API token linked.
Not sure if I need to select some ontologies of interest on the bioportal site. Can you please test?

**Comment by adurbin2** [comment]
Oh, I see plenty on the pulldown (where it used to give the error message)... thank you!

**Comment by e-t-k** [comment]
![screen shot 2017-03-10 at 2 54 15 pm](https://cloud.githubusercontent.com/assets/19291809/23816468/c5feb03c-05a1-11e7-8bcb-71c5c5d921d4.png)

Looks like it works. That's a lot of ontologies.
